### ISSUE TITLE
problem: updating line status is very slow

### ISSUE THREAD

**Issue by gazhayes** [howlongistheline/howlongistheline.org#105]
problem: updating line status is sometimes very slow

The location request currently has to go to the server and back. During peak periods on slow connections this sometimes makes it look like the line isn't being updated.

solution: do the location check on the client side and update the client side UI immediately. Only send it to the server for verification if it passes client side verification.

**Comment by npvn** [comment]
FYI this issue will be resolved as a part of https://github.com/howlongistheline/howlongistheline.org/pull/151.

**Comment by jimkleine** [comment]
@gazhayes I mentioned this issue in one of my recent updates to #155.

We do seem to have made some fixes to at least partly address this in the UI (the "updating" progress bar), but there aren't any pull requests linked to **this** issue.

Do you broadly recall what we have done/tried so far?  Otherwise, I'll dig through the closed pull requests.

**Comment by gazhayes** [comment]
IIRC there were a few things done which fixed this as a side effect. Seems (to me) to be fixed, I'll close it now
