### ISSUE TITLE
problem: store name not showing for some supermarkets

### ISSUE THREAD

**Issue by jillymacnz** [howlongistheline/howlongistheline.org#117]
Some store names not showing, only showing location.

**Comment by gazhayes** [comment]
Thanks @jillymacnz Could you add a screen grab of an example?

**Comment by jimkleine** [comment]
@jillymacnz Thanks for your feedback.  I did spend several hours yesterday tidying up the store names and addresses, but @gazhayes hasn't merged my updates into production yet. This problem might largely go away when that is done.

@gazhayes If you care to send me another dump of the locations collection after the merge, I can review anything newer.

**Comment by jillymacnz** [comment]
@gazhayes  there are two countdowns in highland park and both on Pakuranga Highway.
 Details are as follows:
(This is the main one but no address on ur website)
Highland Park Countdown
507 Pakuranga Highway
Highland Park, Auckland, 2023
(09) 535 4834
![Screenshot_20200411-210752_Chrome](https://user-images.githubusercontent.com/63480645/79040090-36597080-7c3a-11ea-9f77-c764527e54e2.jpg)
also:
This is the smaller one of the two which there is no label and address is incorrect:
Aviemore Drive Countdown
Highland Park Shopping Centre Pakuranga Highway, Pakuranga, Auckland, 2010
(09) 537 6584
![Screenshot_20200411-210740_Chrome](https://user-images.githubusercontent.com/63480645/79040117-5b4de380-7c3a-11ea-998f-34e5ffb26261.jpg)

10 Aylsebury Rd Pakuranga is Countdown Pakuranga
![Screenshot_20200411-210801_Chrome](https://user-images.githubusercontent.com/63480645/79040174-abc54100-7c3a-11ea-9dec-98e487e4e369.jpg)

This would avoid confusion.
Cheers
Jilly Mac

**Comment by jimkleine** [comment]
@gazhayes When I reviewed the data yesterday, I did find a record for 10 Aylesbury St, without a store name.  When I checked Google Streetview, it showed me a carpark, so I flagged it as a duplicate/for removal.  It doesn't really matter because:

Pakuranga (I didn't notice a typo in the store name, though: "Pakaranga") and Highland Park were included in the data update I sent you yesterday, with correct addresses.  There wasn't yet a record for Aviemore Drive in my working copy.  

The "official" (ex Countdown's website) names, addresses and locations for the stores @jillymacnz mentions are:

Countdown Pakuranga: Pakuranga Town Centre, Pakuranga, -36.913,174.8706
Countdown Aviemore Drive: Highland Park Shopping Centre, Pakuranga Highway, Highland Park, -36.8988,174.9067
Countdown Highland Park: 507 Pakuranga Highway, Highland Park, Auckland, -36.8995,174.9082

Four decimal places of accuracy should be sufficient for our locality algorithm, but I'm not completely sure where those points are relative to the store entrances.

**Comment by jillymacnz** [comment]
@gazhayes @jimkleine Thanks guys looking a lot better now and like the new feature of update/confirm option. 👍

**Comment by jillymacnz** [comment]
@gazhayes countdown highland park still has no name. It is still showing as 507 Pakuranga Highway, Highland Park, Auckland
![Screenshot_20200414-134203_Chrome](https://user-images.githubusercontent.com/63480645/79177025-e0f9ab00-7e55-11ea-8e25-0e3e52489a86.jpg)

**Comment by jimkleine** [comment]
@jillymacnz I don't believe any of my updates have been applied to the production database.  I'm going to take this discussion to #133 for now, since that is where @gazhayes has posted his last update. You are welcome to follow along there.

**Comment by jimkleine** [comment]
@jillymacnz All of your local stores should have been updated with their correct addresses now.  Apologies for the delay. :-(

**Comment by jimkleine** [comment]
@jillymacnz I'll continue to keep an eye on this.  I'm closing this issue for now, but we can re-open it if it remains a problem for you.  You will be able to find it under Issues > Closed and you can still add a comment in that state.

**Comment by jillymacnz** [comment]
Hey Jim

Cheers for sorting it all out.

Sorry my email has been playing up so only just got your email come through
now.

Good luck with your very handy project you are involved with,
howlongistheline.

Cheers
Jilly

**Comment by jimkleine** [comment]
@jillymacnz You're welcome :-)

There seems to be at least one person that keeps trying to add another Countdown Highland Park (apparently not realising that the store's official name is Aviemore Drive) and I have been quietly removing them.

NB The e-mail issue might not have been your fault.  Github managed to get a number of its mail servers blacklisted for spamming and they were slow to fix it when I logged a support ticket.  Github's default response when it is unable to deliver e-mail (even when it is their own fault) is to stop trying and to require you to "revalidate" your e-mail address.
