### ISSUE TITLE
problem: "50+" overflows into the next line on mobile

### ISSUE THREAD

**Issue by olliechick** [howlongistheline/howlongistheline.org#142]
it should be in line with "0" and the slider

**Comment by olliechick** [comment]
![Screenshot_20200413-141149](https://user-images.githubusercontent.com/6047072/79086661-f8bb2b80-7d90-11ea-92da-46be627ae4bd.png)

**Comment by gazhayes** [comment]
You could probably just get rid of those numbers altogether now that you show the number while sliding

**Comment by olliechick** [comment]
Yeah, that would probably be better. In that case, it might be good to
permanently display the tooltip on the thumb; I'll see how that feels.

**Comment by jimkleine** [comment]
@olliechick @gazhayes I originally added this comment to #140, but it fits better here.

Without the min/max numbers, there is no sense of scale to the slider, so you have no idea how far to move it until after you have already started to move it.  I suggest this breaks the user's mental model of what this control should look like and how you use it.

The original problem is suggestive of a responsive failure. Do we have a div whose size is not expressed as a percentage somewhere?

**Comment by gazhayes** [comment]
I personally think it's ok without the min/max now that the live number is displayed while sliding it (it was only there originally because there used to be no indication at all). But if you think there's a problem and think it's worth writing a patch that's totally fine of course. Just don't let it revive the original overflow problem.
