### ISSUE TITLE
problem: non-local stores sometimes show up where they shouldn't

### ISSUE THREAD

**Issue by RatMom77** [howlongistheline/howlongistheline.org#152]
I am based in Takanini, Auckland and the second store that appears in my list of stores near me is in kaikohe, Northland some 3.5 hours away. My browser has permission to know my location.

**Comment by olliechick** [comment]
I've just mocked my location as being in Takanini and the top 3 stores for me are Countdown Takanini, Boomerang Superette in Manurewa, and Pak n save takanini.

**Comment by gazhayes** [comment]
I've noticed this kind of thing sometimes too. @RatMom77 can you try a different browser and see if it's the same thing?

**Comment by RatMom77** [comment]
Hmm yes now I get count down, pack n save and rattan alive market but for
the last week it's always had kaikohe? Oh well location seems OK now thanks
Ollie.

**Comment by jimkleine** [comment]
@RatMom77 Welcome to GitHub.  Thanks for the update.  It's always good to know when we do (or don't) fix a problem.

For future reference, it helps us to troubleshoot these kinds of problems if you can:

1.  Indicate the type of device (phone/tablet/desktop) and operating system (Android/iOS/Windows/MacOS etc);

2.  Who your Internet provider ("ISP") is (this might be your phone company if it is your phone and you are using mobile data, but might also be your broadband provider if you are at home and using WiFi at the time) e.g. my desktop thinks it is located in Wellington (I'm not) because that is the geolocation point for my broadband ISP;

3.  The browser being used (Firefox/Chrome/Safari etc);

4.  A screen shot, if you have one.

I'll close this for now, but feel free to add another comment if the problem recurs (you can find it under Issues > "Closed")  and we can re-open it.
