### ISSUE TITLE
problem: location not working

### ISSUE THREAD

**Issue by MadanBhandari** [howlongistheline/howlongistheline.org#176]
problem : Location not working

URL : https://howlongistheline.org/
OS: Ubuntu
error msg on Firefox `ERROR(2): Unknown error acquiring position` 
console error msg on Chromium `Network location provider at 'https://www.googleapis.com/' : No response received.`

also not working with chrome on Android.
same issue on local development setup.

**Comment by gazhayes** [comment]
Hey @MadanBhandari I can't reproduce this and we aren't using google API for this so I guess it's chrome itself trying to get its location from Google, which means it's a browser issue that we can't directly fix.

**Comment by MadanBhandari** [comment]
Problem is `navigator.geolocation.getCurrentPosition()` not working on for both browser on PC and Android device for me.

**Comment by jimkleine** [comment]
@MadanBhandari I suspect this problem is because you are a developer.  This project should be using the browser's geolocation provider, but you may have changed your provider for testing purposes with one of your own projects.  Is that possible?

**Comment by gazhayes** [comment]
> navigator.geolocation.getCurrentPosition() not working on both browser on Ubuntu Laptop and Android device (Chrome)

You could try and see if navigator.geolocation.watchPosition() returns valid results, if so, #172 will fix this.

**Comment by MadanBhandari** [comment]
This problem isn't unique for this project on my laptop (Ubuntu 19.10) and modile (Android 9 on Oneplus 5T), `navigator.geolocation.getCurrentPosition()` isn't working anywhere. 
 - [w3school example](https://www.w3schools.com/html/tryit.asp?filename=tryhtml5_geolocation_error)
- [MDN Example](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API/Using_the_Geolocation_API)

both of the examples are also not working. I tried on two other android devices, one worked without any issue and one had same issue

@jimkleine I haven't changed provider, that must be whatever comes default with device and browser

@gazhayes I have already tried with `navigator.geolocation.watchPosition()`, same issue. There are a lots of stack-overflow questions/answers related to this issue, I believe this issue can occur to many users and non-developer users won't be able explain issue any better. With this issue app can't be used.

**Comment by jimkleine** [comment]
@MadanBhandari  I have just tried your w3schools link with the following results:

1.  Safari on MacOS desktop: Prompts for location permission; returns "Location information is unavailable".  This is **expected behaviour**.  Apple's geolocation provider defaults to using wireless connections only for geolocation.  This Mac has no wireless connectivity; only wired.

2.  Firefox on MacOS desktop: Prompts for location permission; returns correct location (I use Firefox for testing and I'm no longer using the default geolocation provider, so I can specify the location).

3.  Chrome on MacOS desktop: Prompts for location permission; returns a valid location relating to my broadband ISP's location (which is in a different city), but this is expected.

4.  Firefox on Android: Prompts for permission;
a.  Returns "Location information is unavailable" with location services disabled; and
b.  Correct location with location services enabled.

5.  Chrome on Android: Prompts for permission;
a.  Returns "User denied the request for Geolocation" with location services disabled (there is an additional prompt asking you to turn location services on, if they are off: I answered "No", so this message was expected); and
b.  Correct location with location services enabled.

None of my tests returned an error message like you are describing.

Are you able to provide more information about your test specific configuration e.g. browser and version, your Internet connection (are both your mobile and phone using the same WiFi connection when you are testing)?

Are you able to ping www.googleapis.com at the time your error occurs?

NB https://ipinfo.io/geo gives me my ISP's location per (3) above, so definitely not viable here, unfortunately.

**Comment by jimkleine** [comment]
@MadanBhandari Your StackOverflow links are fairly old (8 and 3 years ago respectively).

Have you tried this [StackOverflow solution](https://stackoverflow.com/questions/61032115/unknown-error-acquiring-position-geolocationpositionerror-code-2-firefox-linux)?  It was the first hit when I searched for that Firefox error message.  Mint is a derivative of Ubuntu/Debian.

**Comment by jimkleine** [comment]
@MadanBhandari I have just tried the MDN example and it doesn't work for me on either Firefox or Chrome on MacOS ("Unable to retrieve your location", but no errors like you have described), but something isn't working as expected, because it never asks for permission to use location services like the w3schools demo does, despite being in adjacent browser tabs.

**Comment by MadanBhandari** [comment]
@jimkleine Error message only present at https://howlongistheline.org/, not in w3school & MDN links.
Laptop OS: Ubuntu 19.10
Firefox : 75.0 (64-bit), Mozilla Firefox for for Ubuntu canonical-1.0
Chromium : Version 81.0.4044.113 (Official Build) snap (64-bit)

Mobile: Android 9.0.11 (Oneplus 5T)
Chrome: 81.0.4044.96 - Not working (MDN, w3school links and this app)
Firefox Preview: 4.2.1 (Build #20941431) - all working as expected
Firefox: 68.7.0  - all working as expected

This issue only exist on Chrome on Android, not Firefox and on both (Furefox & Chromium) in Ubuntu, while being on same Wifi Network.

> Are you able to ping www.googleapis.com at the time your error occurs?

Yes

> Have you tried [this StackOverflow solution](https://stackoverflow.com/questions/61032115/unknown-error-acquiring-position-geolocationpositionerror-code-2-firefox-linux)? 

Yes, still same issue.

I have also tested on iPhone 6 on safari, works as expected.

**Comment by jimkleine** [comment]
@MadanBhandari I'm on Firefox 75.0 on MacOS.  Let's try to match geolocation settings (I'll dig out the relevant config options shortly) and see if we can reproduce this.  In the mean time, a couple more questions:

1.  Is the iPhone on the same WiFi network when it works?

2.  How is your WiFi connection routed to the Internet (I'm not seeking personally identifiable information, just trying to understand your configuration)?  Is there a broadband connection between your access point and the Internet and is that a personal connection i.e. this is not shared WiFi in communal housing or commercial premises?

3.  You have referred to a "_local development setup_".  Are you comfortable making changes in about:config in Firefox?

4.  Does the MDN example prompt for location permission from you on Ubuntu/Firefox?

**Comment by MadanBhandari** [comment]
@jimkleine 

> Is the iPhone on the same WiFi network when it works?

No, not in same WiFi. Also I don't have iPhone with me to test again. I took my neighbour phone to check and also asked him to use the app while making run to store. Android is on same WiFi while its working on Firefox but not on Chrome.

>  How is your WiFi connection routed to the Internet (I'm not seeking personally identifiable information, just trying to understand your configuration)? Is there a broadband connection between your access point and the Internet and is that a personal connection i.e. this is not shared WiFi in communal housing or commercial premises?

Private broadband for personal/home use, I am not sure about how its routed, I have access to wifi router.

> You have referred to a "local development setup". Are you comfortable making changes in about:config in Firefox?

Yes, I have updated as per stackoverflow answer, same issue.
updated `geo.provider.network.url` https://www.googleapis.com/geolocation/v1/geolocate?key=test

> Does the MDN example prompt for location permission from you on Ubuntu/Firefox?

No, MDN doesn't ask but w3school example does, still not working. - same on FireFox and Chromium

**Comment by jimkleine** [comment]
My Firefox settings for 75.0 on MacOS (via about:config in the URL bar; after continuing past the Firefox warning, start typing "geo." to limit the configuration items displayed):

![Screen Shot 2020-04-19 at 11 44 21 PM](https://user-images.githubusercontent.com/47098744/79687023-866aaf80-8298-11ea-86de-83017f4f17c3.png)

Notes:
1.  The (two) changes I have made are highlighted in bold (you can revert to the defaults by clicking the rollback icon at the far right).

2.  What these changes do:

a.  I believe geo.provider.use_corelocation relates to Apple's default geolocation provider, which doesn't work for a computer without a WiFi connection, so this just has the effect of forcing the browser to fall back to geo.provider.network.url.  I'm not sure if this will be present on Ubuntu.

b.  The geo.provider.network.url option actually accepts a URI value, so instead of using a network service, I have embedded a JSON snippet that hardcodes a fixed location point.  When you test the w3schools link after making this change, this is the location that it should report.

c.  For anyone wondering, it is the location of a random fire station in Wellington, NZ.  Their reviews claim that they are "not snooty" and that you should bring baked goods if you visit them, "because they deserve it" :-)

**Comment by jimkleine** [comment]
@MadanBhandari With those Firefox settings, this is what I get:

**1. Site result:**

![Screen Shot 2020-04-20 at 12 09 16 AM](https://user-images.githubusercontent.com/47098744/79687477-9a63e080-829b-11ea-9c79-eed8a7280bed.png)

**2.  w3schools Demo:**
![Screen Shot 2020-04-20 at 12 11 08 AM](https://user-images.githubusercontent.com/47098744/79687480-a64fa280-829b-11ea-8f58-5d93a1aaeadc.png)

**3.  Google Maps directions (Fire Station to first store listed on site):**
![Screen Shot 2020-04-20 at 12 10 27 AM](https://user-images.githubusercontent.com/47098744/79687486-acde1a00-829b-11ea-8af3-c23672e2a64d.png)

**Comment by MadanBhandari** [comment]
@jimkleine I am so sorry, I was being stupid. I never checked google maps to check if location is working or not. I was only looking for `navigator.geolocation.getCurrentPosition()` examples only. Google map also not working, it says `Your location could not be determined.`

![Screenshot from 2020-04-19 20-44-09](https://user-images.githubusercontent.com/6429311/79691672-9aa1b300-827e-11ea-824a-2bdf54eb0d06.png)

Still don't know what's causing this, same issue with Android on Chrome. Now I know problem is in my system or brower not the app. Closing this issue.

**Comment by jimkleine** [comment]
@MadanBhandari No problem.  As a next step, since these are both portable devices, I would suggest testing from another location.  That would narrow down whether it is the devices/OS/browsers or something about your home network configuration.

Perhaps Google is trying (and failing) to obtain a location via your IP address/ISP when you are at home?

**Comment by MadanBhandari** [comment]
@jimkleine I have recently did fresh installation of Ubuntu on Laptop after locakdown and I can't imagine how I never face this issue before, even on mobile. Android on same WiFi works on Firefox but not on Chrome and some other android mobile on same WiFi network works as expected. My mobile on cellular data also doesn't work. I will post update here when I find solution for this for future reference.

Thank you for your help :)

**Comment by MadanBhandari** [comment]
UPDATE: Installed Chrome, it's working :), tried re-installing Firefox and Chromium still same error.
