### ISSUE TITLE
problem: no social media preview

### ISSUE THREAD

**Issue by gazhayes** [howlongistheline/howlongistheline.org#50]
problem: there's no preview on social media when sharing the site

**Comment by jimkleine** [comment]
Is this problem related an apparent issue with favicon.ico?  I don't see this file checked in to the repository anywhere, but I'm getting a browser (Firefox) error when I try to display the icon directly:
"The image "https://howlongistheline.org/favicon.ico" cannot be displayed because it contains errors."
I can generate a favicon "bundle" for you if you can supply a suitable image.

If this isn't what you were referring to, please provide an example.

**Comment by gazhayes** [comment]
@jimkleine What I'm referring to is the preview text/image that sites like facebook usually show when you share a link, at the moment nothing very enticing comes up for this site.

However, if you feel like making a favicon that would be cool, whatever image you think looks good :)

**Comment by jimkleine** [comment]
1. I was thinking conceptually along the lines of "how long is a piece of string?", but a quick image search returns very little.  I'll see if I can conjure up a draft logo.
2. For the Facebook links, I there are probably missing metalinks and a suitable image: https://meetedgar.com/blog/facebooks-new-link-previews-need-know-2018/

**Comment by jimkleine** [comment]
@gazhayes I can see you have settled on a logo.  I'll whip up a favicon "bundle" over the next 24 hours. If I put those (static) files in /public, do they find their way to the site's root directory when the project builds?

**Comment by jimkleine** [comment]
Favicon graphics are ready, based on the GitHub logo.  I'll also need to update /client/main.html with the links.  Previews here:
![favicon-32x32](https://user-images.githubusercontent.com/47098744/78683184-175d9480-7943-11ea-9760-b4e3233cf1bc.png)
![apple-touch-icon](https://user-images.githubusercontent.com/47098744/78683050-e715f600-7942-11ea-9b8d-2feb104451b1.png)
@gazhayes I don't currently have a working local build environment (due to Meteor breaking Node on my dev machine).  Where do I need to drop the graphics files for them to find their way to the site root directory (/public or /client)?

**Comment by jimkleine** [comment]
I believe I have solved this: files in /public, but use the root path to reference them from /client/main.html.  I will create a pull request later today.
