### ISSUE TITLE
problem: stores added in wrong location

### ISSUE THREAD

**Issue by gazhayes** [howlongistheline/howlongistheline.org#57]
problem: some people are adding stores in the wrong location.

solution: when a user tries to update the line status but a location failure occurs, allow them to change the store coordinates to their current location.

**Comment by jimkleine** [comment]
When this occurred for me, my update was denied and I got prompted with a question resembling: "Are you really at this store?".

At the time, it seemed like a natural UI implementation would be to allow the user to respond "Yes" and then use some kind of consensus "voting" to converge on the true location (otherwise, one bad actor could spoil many correct geotags in a short period of time).  I'm thinking about how this could be reliably scaled to a large number of stores without creating a large administrator burden.

Whether the associated **queue** update should be accepted might depend on the instantaneous voting weight i.e. if the current votes are converging away from the existing location, we might choose to accept it, but we also don't want to discourage/frustrate users during well-intended updates.

There might also be one additional complication: some stores have two physical entrances, potentially at opposite ends of the store.  This is common where a store is located in a mall and they have one entry into the mall and another with direct access to the carpark (that may be used exclusively during trading hours that extend beyond the standard mall hours).  Entrances are a physical security boundary for the store, so I wouldn't expect them to have more entrances than the minimum necessary for operational reasons i.e. 3+ should be rare.

We have two Walmart stores already.  One is a [potentially 260,000 square foot Supercenter](https://247wallst.com/retail/2014/03/22/walmart-now-has-six-types-of-stores/) and their standard layout seems to imply [two entrances](https://prezi.com/drbfacwp92j-/store-layout-design-and-visual-merchandising-for-walmart/).  These are older links, but retail locations change slowly.

**Comment by gazhayes** [comment]
What about having multiple coordinates per store? If the location is wrong and users want to "update the location" the new coordinates could simple be appended as another valid location. Over time, it will probably become clear which coordinates are real and which ones are outliers based on the number of updates each set receives.

**Comment by jimkleine** [comment]
@gazhayes Initial thoughts on your last comment (yes, I'm being paranoid :-), but security by design is a mostly a good thing):

1.  GPS co-ordinates are quite fine-grained, so that means only adding a location if the locality test fails first (otherwise we would collect a lot of "noise"; I'm aware this might be self-evident, but I'm just making the requirement explicit);

2.  If I was a mischievous PaknSave store owner, surrounded by Countdown stores, and I set my home or store address as an "alternate" location for those stores, then I would be able to toggle all of my competitors' queues to busy and shepherd customers to my store during quiet trading periods (the same principle applies to any bad actor really);

3.  The key to deciding the best implementation for this might be to look first at the design of the purge process and decide what we would need to support that in a sane way?

**Comment by jimkleine** [comment]
I have been trying to think this through visually.  Conceptually, we could allow up to two geotag "clusters" (entrances) per store, calculate the geometric mid-point for each cluster and use only that as a locality comparator in turn (we can test later, but geometric maths might not be fast in Javascript, so keeping this to a minimum for routine queue updates seems like a good idea).

![Store Locations #1](https://user-images.githubusercontent.com/47098744/78487687-a6c84380-779b-11ea-8fec-bdf98d2538bf.jpg)

We could weight each cluster by the number of members (possibly up to some arbitrary limit),  order the cluster mid-points by weight for locality-comparison purposes and then only test the two highest-weighted clusters.  That would automatically exclude outliers over time, **except in the common case where the store has only one entrance**.  Requiring a minimum weight for the second cluster would potentially prevent the second entrance from becoming established.  Perhaps I'm overthinking this?

I haven't yet considered the implementation details/performance implications for MongoDB etc.

**Comment by jimkleine** [comment]
Or we use the geometric mid-point of up to two clusters and tweak the locality radius accordingly?

**Comment by domrosscanada** [comment]
Many of these larger stores Walmart and Costco have moved to dedicated entrances and exits as well as one way shopping. For the larger shops - might be easier to increase GPS capture than use multiple upload points?
