### ISSUE TITLE
problem: there are many duplicate stores

### ISSUE THREAD

**Issue by gazhayes** [howlongistheline/howlongistheline.org#81]
problem: there are many duplicate stores

solution: allow users to remove duplicate stores:

1. add a button to the card rendered for each store "this is a duplicate" or something
2. create a new view where users can select all the other store objects that are referring to the same location (all the duplicates)
3. Take all the data (name, address, coordinates) from all the duplicates. Ask the user which data is best, and combine these into a new object. So, which name is best, which address is best, and which coordinates are best (show a map for each, use openstreetmap).
4. archive all the duplicates into the `archived` collection.

**Comment by jimkleine** [comment]
Suggested mvp:  Display a "duplicate" check box if a store has had no queue updates for more than 24 hours.  Filter the collection to exclude stores with the duplicate flag set (I might do this via a view in the relational world: is there a MongoDB equivalent?).  We could always "recall" them by flipping the flag back.

data clean up:  If I manually clean up the dev database, is there an efficient way to merge those changes back into the live data?

**Comment by jimkleine** [comment]
@gazhayes I will have time tomorrow to clean up the store names and duplicates (and most NZ stores will be closed, making it a good time for this kind of maintenance) if you can give me some guidance on how this is best done i.e. how do I get updates and deletions back into production?

I did ask Countdown for a store list a couple of days ago, but they haven't been forthcoming, so I'll get the branch information from their website.

I should also have a working dev environment by tomorrow, so I will be able to clear some of the other current issues as well.

**Comment by gazhayes** [comment]
@ioioio8888 is currently working on a patch to let users remove duplicate stores so that will probably be the easiest way you to actually do it (rather than working with the database directly).

Will probably be ready tomorrow or the day after

**Comment by jimkleine** [comment]
@gazhayes I wasn't planning on doing this completely manually, but I would like to get it done tomorrow (Friday), if possible, since NZ stores will be closed, Saturday is likely to be a busy day (due to shortened trading hours on Sunday) and the clean-up may save you server resources.

I was thinking more mongoexport (to JSON), programmatic clean-up (including malformed names etc), flag obvious duplicates and then mongoimport.  It looks like we might be able to use $merge  (second answer to this [StackOverflow question](https://stackoverflow.com/questions/11012799/mongodb-how-to-merge-two-collections-databases-together-into-one) if I put the groomed data into a separate temporary collection).

Right now, I'm just focused on getting this done quickly and I can probably work faster in either text or a temporary local relational DB than by getting myself up to speed with the "Mongo way" first.

@ioioio8888 Can you share how/if you prefer to add a duplicate flag?

**Comment by jimkleine** [comment]
@gazhayes I ended up going through these by hand.  I'm nearly finished.  I have:

1.  Made the corrections in a collection called "groomed".  If I can, I'll ZIP it and add it to another comment when I'm finished.  Otherwise, I'll load it to DropBox and e-mail you a link.

2.  I'm using MongoDB v4.2.  There seem to be a **lot of deprecated commands** in this release.  I haven't yet checked whether the StackOverflow merge solution (linked above) still works.

3. @ioioio8888 I have added a boolean field called "isDuplicate".  I defaulted my 333 records to false, but we may need to identify and default any new records added after the dev database dump was taken if your logic relies upon it.

**Comment by gazhayes** [comment]
@jimkleine did you flag just the ones to remove, or also the duplicates that should be kept? I.e. if we just remove everything you flagged, would we be losing listings that we need to keep?

**Comment by jimkleine** [comment]
@gazhayes Where I had more than one "candidate", I chose the one with the best address information, left it with isDuplicate=false, and flagged the other(s) as isDuplicate=true, which means that you could filter/delete everything with isDuplicate=true and not lose anything useful.

**Comment by jimkleine** [comment]
@gazhayes To clarify why I made that choice, I noticed yesterday PM that you have currently have live logic to update the location, so even if I didn't select the best location data, that should shake itself out.

**Comment by gazhayes** [comment]
@jimkleine  Cool, I should be able to use that then!

Can you email it to me? gareth.hayes@gmail.com

**Comment by jimkleine** [comment]
@gazhayes Sure.  Just one caveat that I only recently noticed: the dev database still has some old fields e.g. queue status is no/small/long, so there have been schema changes that you will have to work around.

**Comment by gazhayes** [comment]
That's ok I'll massage it into something useful

**Comment by jimkleine** [comment]
@gazhayes Sent.
